import type {
  Application,
  Category,
  City,
  FairApplication,
  JobVacancy,
  Listing,
  ListingKind,
  Payment,
  Profession,
  SpecialistProfile,
  Tariff,
  UserProfile,
  WorkRequest,
} from "./types";

export const region = {
  slug: "krasnodarskiy-kray",
  name: "Краснодарский край",
};

export const cities: City[] = [
  { slug: "abinsk", name: "Абинск", regionSlug: region.slug },
  { slug: "anapa", name: "Анапа", regionSlug: region.slug },
  { slug: "apsheronsk", name: "Апшеронск", regionSlug: region.slug },
  { slug: "armavir", name: "Армавир", regionSlug: region.slug },
  { slug: "belorechensk", name: "Белореченск", regionSlug: region.slug },
  { slug: "gelendzhik", name: "Геленджик", regionSlug: region.slug },
  { slug: "goryachiy-klyuch", name: "Горячий Ключ", regionSlug: region.slug },
  { slug: "gulkevichi", name: "Гулькевичи", regionSlug: region.slug },
  { slug: "eysk", name: "Ейск", regionSlug: region.slug },
  { slug: "korenovsk", name: "Кореновск", regionSlug: region.slug },
  { slug: "krasnodar", name: "Краснодар", regionSlug: region.slug },
  { slug: "kropotkin", name: "Кропоткин", regionSlug: region.slug },
  { slug: "krymsk", name: "Крымск", regionSlug: region.slug },
  { slug: "kurganinsk", name: "Курганинск", regionSlug: region.slug },
  { slug: "labinsk", name: "Лабинск", regionSlug: region.slug },
  { slug: "novokubansk", name: "Новокубанск", regionSlug: region.slug },
  { slug: "novorossiysk", name: "Новороссийск", regionSlug: region.slug },
  { slug: "primorsko-akhtarsk", name: "Приморско-Ахтарск", regionSlug: region.slug },
  { slug: "slavyansk-na-kubani", name: "Славянск-на-Кубани", regionSlug: region.slug },
  { slug: "sochi", name: "Сочи", regionSlug: region.slug },
  { slug: "temryuk", name: "Темрюк", regionSlug: region.slug },
  { slug: "timashevsk", name: "Тимашевск", regionSlug: region.slug },
  { slug: "tikhoretsk", name: "Тихорецк", regionSlug: region.slug },
  { slug: "tuapse", name: "Туапсе", regionSlug: region.slug },
  { slug: "ust-labinsk", name: "Усть-Лабинск", regionSlug: region.slug },
  { slug: "khadyzhensk", name: "Хадыженск", regionSlug: region.slug },
];

export const categories: Category[] = [
  { slug: "nedvizhimost", name: "Недвижимость", children: ["Продам недвижимость", "Куплю недвижимость", "Аренда", "Коммерческая недвижимость"] },
  { slug: "transport", name: "Авто", children: ["Продам авто", "Куплю авто", "Мототехника", "Запчасти"] },
  { slug: "elektronika", name: "Электроника", children: ["Смартфоны", "Ноутбуки", "Компьютеры", "Аудио и видео", "Игровые приставки"] },
  { slug: "antikvariat-i-kollektsii", name: "Антиквариат и коллекции", children: ["Товары времен СССР", "Картины и живопись"] },
  { slug: "zhivotnye", name: "Животные", children: ["Домашние питомцы", "Сельхоз животные", "Экзотические животные"] },
  { slug: "biznes", name: "Бизнес", children: ["Продам бизнес", "Куплю бизнес", "Оборудование", "Партнерство"] },
  { slug: "krasota-i-uhod", name: "Красота и уход", children: ["Парикмахеры", "Маникюр и педикюр"] },
  { slug: "meditsina", name: "Медицина", children: ["Медицинский персонал", "Уход на дому"] },
  { slug: "mebel-i-interer", name: "Мебель и интерьер", children: ["Мебель"] },
  { slug: "otdyh", name: "Отдых", children: ["Турбазы", "Гостиницы", "Походы"] },
  { slug: "rabota", name: "Работа", children: ["Вакансии", "Анкеты специалистов"] },
  { slug: "remont-i-stroitelstvo", name: "Ремонт и строительство", children: ["Ремонт квартир", "Сантехника"] },
  { slug: "sad-i-rasteniya", name: "Сад и растения", children: ["Цветы и саженцы"] },
  { slug: "tovary-i-veshchi", name: "Товары и вещи", children: ["Выкройки и рукоделие"] },
  { slug: "uslugi-dlya-doma", name: "Услуги для дома", children: ["Клининг"] },
  {
    slug: "ritualnye-uslugi",
    name: "Ритуальные услуги",
    children: [
      "Кремация",
      "Уход за местом захоронения",
      "Транспортирование останков",
      "Подготовка тела к погребению",
      "Предпохоронное содержание останков",
      "Захоронение и сопутствующие работы",
      "Организация и проведение обряда прощания",
      "Продажа и изготовление похоронных принадлежностей",
      "Изготовление, установка и демонтаж намогильных сооружений",
    ],
  },
  { slug: "yarmarka-masterov", name: "Ярмарка мастеров", children: ["Мебель", "Посуда", "Макраме", "Одежда и текстиль", "Разное", "Саженцы и рассада"] },
  { slug: "znakomstva", name: "Знакомства", children: [] },
];

export const listingKinds: Array<{ slug: ListingKind; name: string; description: string }> = [
  { slug: "prodam", name: "Продам", description: "Товары, вещи и услуги от жителей края" },
  { slug: "kuplyu", name: "Куплю", description: "Заявки покупателей и поиск нужных вещей" },
  { slug: "arenda", name: "Аренда", description: "Бронирование жилья, турбаз, гостиниц и активного отдыха" },
  { slug: "menyayu", name: "Меняю", description: "Обмен товарами, материалами и услугами" },
  { slug: "otdam-darom", name: "Отдам даром", description: "Полезные вещи без оплаты" },
];

export const listings: Listing[] = [
  {
    id: "1",
    slug: "prodam-mebel-krasnodar-1",
    kind: "prodam",
    categorySlug: "mebel-i-interer",
    subcategory: "Мебель",
    author: "Анна",
    title: "Комод из массива дерева",
    description: "Аккуратный комод для спальни, самовывоз из Краснодара. Есть небольшие следы использования.",
    city: "Краснодар",
    district: "Фестивальный район",
    lat: 45.056,
    lng: 38.958,
    showExactAddress: false,
    price: "12 500 ₽",
    delivery: {
      enabled: true,
      services: ["cdek", "russian-post"],
      payer: "buyer",
      originCity: "Краснодар",
      packageWeightGram: 18000,
      packageLengthCm: 90,
      packageWidthCm: 45,
      packageHeightCm: 80,
      handlingDays: 2,
      comment: "Отправка после согласования упаковки с покупателем.",
    },
    imageTone: "amber",
    phone: "+78610002001",
    status: "published",
    paid: true,
    publishedAt: "2026-05-20",
    expiresAt: "2026-06-19",
  },
  {
    id: "2",
    slug: "kuplyu-sazhentsy-sochi-2",
    kind: "kuplyu",
    categorySlug: "sad-i-rasteniya",
    subcategory: "Цветы и саженцы",
    author: "Игорь",
    title: "Куплю саженцы гортензии",
    description: "Ищу 10-15 здоровых саженцев для участка. Рассмотрю Сочи и ближайшие поселки.",
    city: "Сочи",
    district: "Центральный район",
    lat: 43.585,
    lng: 39.723,
    showExactAddress: false,
    price: "до 7 000 ₽",
    imageTone: "emerald",
    messengerUrl: "https://wa.me/78610002002",
    status: "published",
    paid: true,
    publishedAt: "2026-05-21",
    expiresAt: "2026-06-20",
  },
  {
    id: "3",
    slug: "menyayu-instrument-novorossiysk-3",
    kind: "menyayu",
    categorySlug: "remont-i-stroitelstvo",
    subcategory: "Ремонт квартир",
    author: "Сергей",
    title: "Меняю набор электроинструмента",
    description: "Обменяю комплект инструмента на материалы для ремонта или садовую технику.",
    city: "Новороссийск",
    district: "Приморский район",
    lat: 44.724,
    lng: 37.768,
    showExactAddress: false,
    imageTone: "slate",
    phone: "+78610002003",
    status: "published",
    paid: true,
    publishedAt: "2026-05-22",
    expiresAt: "2026-06-21",
  },
  {
    id: "4",
    slug: "otdam-knigi-anapa-4",
    kind: "otdam-darom",
    categorySlug: "tovary-i-veshchi",
    subcategory: "Выкройки и рукоделие",
    author: "Мария",
    title: "Отдам книги по рукоделию",
    description: "Подборка журналов и книг, все в хорошем состоянии. Забрать можно вечером.",
    city: "Анапа",
    district: "12-й микрорайон",
    lat: 44.894,
    lng: 37.316,
    showExactAddress: false,
    imageTone: "rose",
    messengerUrl: "https://t.me/blizhniy_support",
    status: "published",
    paid: true,
    publishedAt: "2026-05-23",
    expiresAt: "2026-06-22",
  },
];

export const professions: Profession[] = [
  { parent: "Юридические услуги", name: "Юрист", slug: "yurist", active: true },
  { parent: "Красота и уход", name: "Швея", slug: "shveya", active: true },
  { parent: "Ремонт и строительство", name: "Сварщик", slug: "svarshchik", active: true },
  { parent: "Образование", name: "Репетитор английского языка", slug: "repetitor-angliyskogo", active: true },
  { parent: "Ремонт и строительство", name: "Сантехник", slug: "santehnik", active: true },
  { parent: "Красота и уход", name: "Парикмахер", slug: "parikmaher", active: true },
  { parent: "Красота и уход", name: "Мастер маникюра", slug: "master-manikyura", active: true },
  { parent: "Услуги для дома", name: "Клининг-специалист", slug: "klining-spetsialist", active: true },
  { parent: "Медицина", name: "Сиделка", slug: "sidelka", active: true },
  { parent: "Медицина", name: "Медсестра", slug: "medsestra", active: true },
  { parent: "Ремонт и строительство", name: "Плиточник", slug: "plitochnik", active: true },
  { parent: "Ремонт и строительство", name: "Электрик", slug: "elektrik", active: true },
  { parent: "Ремонт и строительство", name: "Мастер ремонта квартир", slug: "master-remonta-kvartir", active: true },
  { parent: "Мебель и интерьер", name: "Мебельщик", slug: "mebelshchik", active: true },
];

export const vacancies: JobVacancy[] = [
  {
    id: "santehnik-remdom-123",
    organization: "ООО РемДом",
    title: "Сантехник",
    profession: "Сантехник",
    city: "Краснодар",
    district: "Центральный округ",
    address: "ул. Красная, 118",
    lat: 45.037,
    lng: 38.975,
    showExactAddress: true,
    salary: "от 80 000 ₽",
    logoText: "РемДом",
    logoTone: "blue",
    phone: "+78610000001",
    email: "hr@remdom.example",
    schedule: "5/2, выездные заявки",
    description: "Обслуживание квартир и частных домов, аварийные и плановые заявки.",
    requirements: "Опыт от 1 года, аккуратность, свой базовый инструмент.",
    responsibilities: "Монтаж, диагностика, ремонт, общение с заказчиками.",
    status: "published",
  },
  {
    id: "master-manikyura-liliya-124",
    organization: "Студия Красоты Лилия",
    title: "Мастер маникюра",
    profession: "Мастер маникюра",
    city: "Сочи",
    district: "Центральный район",
    address: "ул. Навагинская, 9",
    lat: 43.591,
    lng: 39.727,
    showExactAddress: true,
    salary: "от 60 000 ₽",
    logoText: "Лилия",
    logoTone: "violet",
    messengerUrl: "https://wa.me/78610000002",
    email: "liliya@example.test",
    schedule: "Сменный график",
    description: "Рабочее место в студии красоты с готовой клиентской базой.",
    requirements: "Портфолио, санитарная книжка, аккуратность.",
    responsibilities: "Маникюр, педикюр, дизайн, запись клиентов.",
    status: "published",
  },
  {
    id: "kliner-clean-home-125",
    organization: "Clean Home",
    title: "Клинер",
    profession: "Клининг-специалист",
    city: "Новороссийск",
    district: "Центральный район",
    address: "ул. Советов, 42",
    lat: 44.724,
    lng: 37.768,
    showExactAddress: true,
    salary: "от 45 000 ₽",
    logoText: "Clean Home",
    logoTone: "teal",
    email: "clean@example.test",
    schedule: "Гибкий график",
    description: "Клининг квартир и домов по заявкам заказчиков.",
    requirements: "Ответственность и пунктуальность.",
    responsibilities: "Поддерживающая и генеральная уборка.",
    status: "published",
  },
];

export const workRequests: WorkRequest[] = [
  {
    id: "request-remont-dachi-201",
    author: "Ольга",
    title: "Нужен мастер для ремонта дачной кухни",
    description: "Частный заказ: заменить столешницу, подключить мойку и собрать небольшой шкаф.",
    profession: "Мастер ремонта квартир",
    city: "Краснодар",
    district: "Прикубанский округ",
    address: "пос. Российский",
    lat: 45.111,
    lng: 39.05,
    showExactAddress: false,
    budget: "до 25 000 ₽",
    phone: "+78610003001",
    messengerUrl: "https://wa.me/78610003001",
    status: "published",
    createdAt: "2026-05-22",
    publishedAt: "2026-05-23",
  },
  {
    id: "request-poshiv-shtor-202",
    author: "Марина",
    title: "Пошив штор для гостевого дома",
    description: "Нужен исполнитель с выездом и замером, 8 окон, ткань обсуждается отдельно.",
    profession: "Швея",
    city: "Анапа",
    district: "Высокий берег",
    lat: 44.9,
    lng: 37.32,
    showExactAddress: false,
    budget: "от 18 000 ₽",
    phone: "+78610003002",
    status: "published",
    createdAt: "2026-05-24",
    publishedAt: "2026-05-24",
  },
  {
    id: "request-santehnik-hostel-203",
    author: "Гостевой дом Морской",
    title: "Разовая заявка сантехника",
    description: "Проверить давление воды и заменить смесители в двух номерах.",
    profession: "Сантехник",
    city: "Геленджик",
    district: "Толстый мыс",
    address: "ул. Приморская, 12",
    lat: 44.56,
    lng: 38.08,
    showExactAddress: true,
    budget: "10 000 ₽",
    messengerUrl: "https://t.me/blizhniy_support",
    phone: "+78610003003",
    status: "published",
    createdAt: "2026-05-25",
    publishedAt: "2026-05-25",
  },
];

export const specialists: SpecialistProfile[] = [
  {
    id: "santehnik-aleksandr-123",
    name: "Александр",
    profession: "Сантехник",
    skills: "Монтаж, ремонт, замена",
    city: "Краснодар",
    district: "Фестивальный район",
    lat: 45.056,
    lng: 38.958,
    showExactAddress: false,
    price: "от 1 500 ₽",
    imageSeed: "alex",
    phone: "+78610001001",
    messengerUrl: "https://t.me/blizhniy_support",
    status: "published",
  },
  {
    id: "manikyur-marina-124",
    name: "Марина",
    profession: "Мастер маникюра",
    skills: "Маникюр, педикюр, дизайн",
    city: "Сочи",
    district: "Центральный район",
    lat: 43.585,
    lng: 39.723,
    showExactAddress: false,
    price: "от 1 200 ₽",
    imageSeed: "marina",
    phone: "+78610001002",
    messengerUrl: "https://wa.me/78610001002",
    status: "published",
  },
  {
    id: "repetitor-irina-125",
    name: "Ирина",
    profession: "Репетитор английского",
    skills: "Подготовка, разговорный английский",
    city: "Краснодар",
    district: "Юбилейный район",
    lat: 45.02,
    lng: 38.93,
    showExactAddress: false,
    price: "от 900 ₽",
    imageSeed: "irina",
    phone: "+78610001003",
    videoUrl: "https://meet.google.com/",
    status: "published",
  },
];

export const tariffs: Tariff[] = [
  { id: "listing-publication", name: "Размещение объявления", action: "listing_publication", price: 199, durationDays: 30, active: true },
  { id: "vacancy-publication", name: "Размещение вакансии", action: "vacancy_publication", price: 499, durationDays: 30, active: true },
  { id: "ad-marquee", name: "Реклама в бегущей строке", action: "ad_marquee", price: 299, durationDays: 7, active: true },
  { id: "job-response", name: "Отклик на вакансию", action: "job_response", price: 99, durationDays: null, active: true },
  { id: "fair-participation", name: "Участие в ярмарке мастеров", action: "fair_participation", price: 1000, durationDays: null, active: true },
];

export const fairCategories = ["Мебель", "Посуда", "Макраме", "Одежда и текстиль", "Разное", "Саженцы и рассада"];

export const fairApplications: FairApplication[] = [
  {
    id: "fair-001",
    participantName: "Мастерская Кубань Дуб",
    city: "Краснодар",
    category: "Мебель",
    description: "Столы, полки и небольшая мебель из массива. Принимаем индивидуальные заказы после ярмарки.",
    productPhotos: ["Стол из дуба", "Полка для кухни"],
    videoUrl: "https://rutube.ru/",
    phone: "+78610004001",
    email: "oak@example.test",
    comment: "Нужен стол 2x2 метра и доступ к розетке.",
    status: "published",
    paymentStatus: "succeeded",
    address: "ул. Красная, 5",
    district: "Центральный округ",
    lat: 45.035,
    lng: 38.976,
    showExactAddress: true,
    createdAt: "2026-05-12",
  },
  {
    id: "fair-002",
    participantName: "Теплые узлы",
    city: "Сочи",
    category: "Макраме",
    description: "Панно, кашпо и декор ручной работы. Покажем коллекцию для веранд и гостевых домов.",
    productPhotos: ["Панно", "Кашпо"],
    videoUrl: "https://vkvideo.ru/",
    phone: "+78610004002",
    email: "macrame@example.test",
    status: "published",
    paymentStatus: "succeeded",
    district: "Центральный район",
    lat: 43.585,
    lng: 39.723,
    showExactAddress: false,
    createdAt: "2026-05-16",
  },
  {
    id: "fair-003",
    participantName: "Рассада у моря",
    city: "Анапа",
    category: "Саженцы и рассада",
    description: "Саженцы инжира, лаванды, гортензии и сезонная рассада для частных участков.",
    productPhotos: ["Саженцы", "Рассада"],
    phone: "+78610004003",
    email: "sad@example.test",
    comment: "Нужна тень для растений.",
    status: "pending_payment",
    paymentStatus: "pending",
    district: "12-й микрорайон",
    lat: 44.894,
    lng: 37.316,
    showExactAddress: false,
    createdAt: "2026-05-20",
  },
];

export const users: UserProfile[] = [
  { id: "u1", name: "Анна", email: "anna@example.test", phone: "+78610002001", roleLabel: "Продавец", blocked: false },
  { id: "u2", name: "ООО РемДом", email: "hr@remdom.example", phone: "+78610000001", roleLabel: "Организация", blocked: false },
  { id: "u3", name: "Александр", email: "alex@example.test", phone: "+78610001001", roleLabel: "Специалист", blocked: false },
];

export const payments: Payment[] = [
  {
    id: "pay-listing-1",
    targetType: "listing",
    targetId: "1",
    targetTitle: "Комод из массива дерева",
    tariffId: "listing-publication",
    amount: 199,
    status: "succeeded",
    provider: "mock",
    createdAt: "2026-05-20",
    paidAt: "2026-05-20",
  },
  {
    id: "pay-vacancy-1",
    targetType: "vacancy",
    targetId: "santehnik-remdom-123",
    targetTitle: "Сантехник",
    tariffId: "vacancy-publication",
    amount: 499,
    status: "succeeded",
    provider: "mock",
    createdAt: "2026-05-20",
    paidAt: "2026-05-20",
  },
  {
    id: "pay-response-1",
    targetType: "application",
    targetId: "app-1",
    targetTitle: "Отклик Александра на вакансию сантехника",
    tariffId: "job-response",
    amount: 99,
    status: "created",
    provider: "mock",
    createdAt: "2026-05-25",
  },
];

export const applications: Application[] = [
  {
    id: "app-1",
    vacancyTitle: "Сантехник",
    specialistName: "Александр",
    status: "pending_payment",
    paymentId: "pay-response-1",
  },
];
